### ISSUE TITLE
Cool idea! 

### ISSUE THREAD

**Issue by mikhael28** [multifol-io/site#314]
The financial variables info is pretty interesting, I like the idea of standardizing some of these data structures into a common pattern/json blob that would be easy to consume. Are you working on all this by yourself? In the name of Loki, you have written a lot of Issues.

**Comment by rrelyea** [comment]
Thanks for the feedback!

Yes, I'm the only contributor for multifol.io/financial-variables and multifol.io/site.
I've gotten a lot of feedback (mostly on bogleheads.org forums)...and yes, I like writing down and prioritizing issues...but several projects contend for my attention.
